config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', invitations: 'invitations' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    get 'topics/unassign_team' => 'topics#unassign_team', as: :unassign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    # Export Routes
    get 'backups' => 'backups#index', as: :backups
    get 'backups/export' => "backups/export", as: :export_backup
    get  'backups/download' => "backups/download", as: :download
    delete 'backups/:id(.:format)', :to => 'backups#destroy', as: :delete_backup

    # Import Routes
    resources :imports, only: [:index, :show]
    post 'imports/restore' => "importz/restore", as: :import_restore

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    get 'internal_docs/search' => 'internal_categories#search', as: :internal_docs_search

    resources :categories do
      resources :docs, except: [:index, :show]
    end


    resources :internal_categories, only: [:index, :show] do
      resources :internal_docs, only: :show
    end

    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    post 'users/:id/scrub' => 'users#scrub', as: :scrub_user
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  login                  :string
#  identity_url           :string
#  name                   :string
#  admin                  :boolean          default(FALSE)
#  bio                    :text
#  signature              :text
#  role                   :string           default("user")
#  home_phone             :string
#  work_phone             :string
#  cell_phone             :string
#  company                :string
#  street                 :string
#  city                   :string
#  state                  :string
#  zip                    :string
#  title                  :string
#  twitter                :string
#  linkedin               :string
#  thumbnail              :string
#  medium_image           :string
#  large_image            :string
#  language               :string           default("en")
#  assigned_ticket_count  :integer          default(0)
#  topics_count           :integer          default(0)
#  active                 :boolean          default(TRUE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  provider               :string
#  uid                    :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#  invitations_count      :integer          default(0)
#  invitation_message     :text
#  time_zone              :string           default("UTC")
#  profile_image          :string
#  notify_on_private      :boolean          default(FALSE)
#  notify_on_public       :boolean          default(FALSE)
#  notify_on_reply        :boolean          default(FALSE)
#  account_number         :string
#  priority               :string           default("normal")
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => Devise.omniauth_providers

  INVALID_NAME_CHARACTERS = /\A('|")|('|")\z/

  # Add preferences to user model
  include RailsSettings::Extend

  TEMP_EMAIL_PREFIX = 'change@me'

  attr_accessor :opt_in

  validates :name, presence: true, format: { with: /\A\D+\z/ }
  validates :email, presence: true


  include Gravtastic
  mount_uploader :profile_image, ProfileImageUploader

  include PgSearch
  pg_search_scope :user_search,
                  against: [:name, :login, :email, :company, :account_number, :home_phone, :work_phone, :cell_phone]

  paginates_per 15

  # Relationships

  has_many :topics, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :docs
  has_many :backups, dependent: :delete_all
  has_many :api_keys, dependent: :destroy

  has_attachment  :avatar, accept: [:jpg, :png, :gif]
  is_gravtastic

  after_invitation_accepted :set_role_on_invitation_accept
  after_create :enable_notifications_for_admin
  before_save :reject_invalid_characters_from_name
  acts_as_taggable_on :teams

  ROLES = %w[admin agent editor user]

  # TODO: Will want to refactor this using .or when upgrading to Rails 5
  scope :admins, -> { where('admin = ? OR role = ?',true,'admin').order('name asc') }
  scope :agents, -> { where('admin = ? OR role = ? OR role = ?',true,'admin','agent').order('name asc') }
  scope :customers, -> { where('admin = ? and role = ?',false,'user').where.not(role: ['agent','admin','editor']).where.not(id: 2).order('name asc') }
  scope :team, -> { where('admin = ? OR role = ? OR role = ? OR role = ?',true,'admin','agent','editor').order('name asc') }
  scope :active, -> { where(active: true)}
  scope :by_role, -> (role) { where(role: role) }

  def set_role_on_invitation_accept
    self.role = self.role.presence || "agent"
    self.active = true
    self.save
  end

  def enable_notifications_for_admin
    if self.role == "admin"
      self.notify_on_private = true
      self.notify_on_public = true
      self.notify_on_reply = true
    end
  end

  # Permanently destroy a user along with all owned records
  # change doc ownership
  def permanently_destroy
    return if self.is_admin?
    return if self.id == 2 #prevent the system user from being destroyed

    DeleteUserJob.perform_later(self.id)
  end

  # Removes or anonymizes associated records
  def scrub
    return if self.is_admin?
    return if self.id == 2 #prevent the system user from anonymized

    # unassign from any topics assigned to
    self.unassign_all

    # "forget user"
    self.anonymize
  end

  # anonymizes a users attributes
  def anonymize
    return if self.is_admin?

    # anonymize own attributes
    self.update!(
      login: 'anon',
      name: 'Anonymous User',
      role: 'user',
      signature: nil,
      home_phone: nil,
      work_phone: nil,
      cell_phone: nil,
      company: nil,
      street: nil,
      city: nil,
      state: nil,
      zip: nil,
      title: nil,
      twitter: nil,
      linkedin: nil,
      bio: nil,
      thumbnail: nil,
      medium_image: nil,
      large_image: nil,
      profile_image: nil,
      current_sign_in_ip: nil,
      last_sign_in_ip: nil,
      encrypted_password: SecureRandom.hex(24),
      account_number: nil,
      active: false,
      email: 'change@me-' + SecureRandom.hex(5) + '.anonymous'
    )

    # anonymize cached attributes (topics)
    self.topics.update_all(user_name: 'Anonymized User')

    # rebuild index
  end

  # Unassign from all tickets
  def unassign_all
    Topic.where(assigned_user_id: self.id).update_all(assigned_user_id: nil)
  end

  # Can this user be deleted? Protects admins/system user from accidental delete
  def can_scrub_and_delete?
    return false if self.id == 2 || self.is_admin?
    true
  end

  def self.notifiable_on_public
    agents.where(notify_on_public: true).reorder('id asc')
  end

  def self.notifiable_on_private
    agents.where(notify_on_private: true).reorder('id asc')
  end

  def self.notifiable_on_reply
    agents.where(notify_on_reply: true).reorder('id asc')
  end

  def active_assigned_count
    Topic.where(assigned_user_id: self.id).active.count
  end

  def is_restricted?
    self.team_list.count > 0 && !self.is_admin?
  end

  def self.create_password
    Devise.friendly_token
  end

  def thumbnail_url
    self.thumbnail.blank? ? self.gravatar_url(size: 60) : self.thumbnail
  end

  def image_url
    self.medium_image || self.gravatar_url(size: 60)
  end

  def self.find_for_oauth(auth)
    user = find_by(email: auth.info.email)
    if user
      user.tap do |u|
        u.provider = auth.provider
        u.uid = auth.uid
        u.save!
      end
    else
      # NOTE: this stopped working with the test, not sure why. Replaced with
      # find_or_create_by and everything passed again:

      # where(provider: auth.provider, uid: auth.uid).first_or_create do |u|
      # it turns out that is not part of the public rails api, despite being
      # used in the wild. https://github.com/rails/rails/issues/23495

      find_or_create_by(provider: auth.provider, uid: auth.uid) do |u|
        u.email = auth.info.email.present? ? auth.info.email : u.temp_email(auth)
        u.name = auth.info.name.present? ? auth.info.name : "Name Missing"
        u.role = 'user'
        u.thumbnail = auth.info.image
        u.password = Devise.friendly_token[0,20]
      end
    end
  end

  def temp_email(auth)
    "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com"
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def signup_guest
    enc = Devise.token_generator.generate(User, :reset_password_token)
    self.reset_password_token = enc
    self.reset_password_sent_at = Time.now.utc

    self.login = self.email.split("@")[0]
    self.password = User.create_password
    self.save
  end

  # evaluates to true if they are a priority (high/vip) user
  def priority?
    self.priority == 'high' || self.priority == 'vip'
  end

  # NOTE: Could have user AR Enumerables for this, but the field was already in the database as a string
  # and changing it could be painful for upgrading installed users. These are three
  # Utility methods for checking the role of an admin:

  def is_admin?
    self.role == 'admin'
  end

  def is_agent?
    %w( agent admin ).include?(self.role)
  end

  def is_editor?
    %w( editor agent admin ).include?(self.role)
  end

  def self.bulk_invite(emails, message, role)
    #below line merge comma saperated emails as well as emails saperated by new lines
    emails = emails.each_line.reject { |l| l =~ /^\s+$/ }.map { |l| l.strip.split(', ') }.flatten

    emails.each do |email|
      is_valid_email = email.match('^.+@.+$')
      if is_valid_email
        User.invite!({email: email}) do |user|
          user.invitation_message = message
          user.name = "Invited User: #{email}"
          user.role = role
          user.active = false
        end
      end
    end
  end

  #when using deliver_later attr_accessor :message becomes nil on mailer view
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  # check if user is active or not
  def active_for_authentication?
    super && self.active?
  end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper

  def ticket_page_title
    concat j ticket_status_label
    concat j new_ticket_button
    concat j ticket_nav_dropdown
  end

  def user_page_title

  end

  def ticket_status_label
    content_tag :span, class: "label #{status_class(@status)}", style: 'text-transform: uppercase' do
      status_label(@status)
    end
  end

  def new_ticket_button
    content_tag :span, class: 'hidden-xs pull-right' do
      link_to t(:open_new_discussion, default: 'Open Discussion'), new_admin_topic_path, remote: true, class: 'btn btn-primary'
    end
  end

  def ticket_nav_dropdown
    render partial: 'admin/topics/ticket_nav_dropdown'
  end

  def user_priority(user)
    return unless user.priority?
    content_tag :span, class: 'label label-tag', style: 'text-transform: uppercase' do
      user.priority
    end
  end

end

app/views/admin/topics/_post.html.erb
<!-- Admin post partial -->
<div id="post-<%= post.id %>" class="media post-container disallow-post-voting <%= "kind-#{post.kind}" %><%= " inactive" unless post.active? %> overflow-visible" <%= 'style="display:none;"' if post.kind == 'note' %>>
	<div class="pull-left">
		<%= avatar_image(post.user, size=40) %>
	</div>
	<div class="media-body media-right overflow-visible">
		<span class="hidden-sm hidden-md hidden-lg"><%= last_active_time(post.created_at) %><br/></span>
		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
			<%= post_message(post,true) %>
			<ul class="dropdown-menu dropdown-menu-left" role="menu">
				<li><%= link_to t('edit', default: "Edit"), edit_admin_post_path(post), remote: true %></li>
				<li><%= link_to t('convert_content', default: 'Turn post into content'), new_admin_doc_path(post_id: post.id, lang: I18n.locale) %></li>
        <li><%= link_to t('new_discussion', default: 'Create new discussion from this'), admin_split_topic_path(topic_id: post.topic_id, post_id: post.id), method: :post, remote: true %></li>
        <li><%= link_to t('change_owner', default: 'Change author'), '#', data: { toggle: "modal", target: "#change-user-modal-#{post.id}" } %></li>
        <%= content_tag :li, link_to(t('Show Raw Email', default: 'Raw Email'), admin_post_raw_path(post), target: 'blank') if post.raw_email.present? %>
			</ul>
		</span>

		<span class="last-active posted-at less-important pull-right">
			<span class="hidden-xs">
			<%= last_active_time(post.created_at) %>
			</span>
		</span>
		<%= content_tag :div, post.cc.present? ? "cc: #{post.cc}" : "", class: 'post-cc post-cc-style' %>
		<%= content_tag :div, post.bcc.present? ? "bcc: #{post.bcc}" : "", class: 'post-bcc post-cc-style' %>
		<div id="post-body-<%= post.id %>" class="post-body less-important text-left">
			<%= simple_format(post.body) -%>
      <%= render partial: 'posts/thumbnail', locals: { :model_name => post } %>
			<%= render partial: 'posts/attachment', locals: { :model_name => post } %>
		</div>

	</div>

  <div id="change-user-modal-<%= post.id %>" class="modal fade change-user-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"><%= t('change_owner', default: 'Change author') %></h4>
        </div>

        <div class="modal-body row">
          <div class="col-md-12">
            <%= bootstrap_form_tag url: admin_user_search_path, method: 'post', remote: true, html: { class: 'search_form' } do |f| -%>
              <%= hidden_field_tag 'post_id', post.id %>
              <%= f.text_field :user_search, skip_label: true, placeholder: 'Type users name or email', autocomplete: :off, onkeyup: "search_user(#{post.id})" -%>
            <% end -%>
            <div class="search-results">
            </div>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>

app/views/admin/topics/_topic.html.erb
<tr id="topic-<%= topic.id %>" class="topic border-bottom link-row admin-discussion">
  <td>
    <%= check_box_tag "topic_ids[]", topic.id, false, class: 'topic-checkbox pull-left' %>
    <span class="user-thumbnail pull-right hidden-xs">
      <%= link_to avatar_image(topic.user, size=40), admin_user_path(topic.user.id), remote: true %>
    </span>
  </td>

  <td>
      <span class="more-important truncate-ellipsis">
        <%= link_to "##{topic.id}- #{topic.name}", admin_topic_path(topic), remote: true, class: "click-loader topic-link topic-link-#{topic.id}" -%>
        <%= badge_for_status(topic.current_status) %>
        <%= badge_for_private if forums? and topic.private? %>
        <% tag_listing(topic.team_list) %>
      </span>
    <span class="less-important user-link">
      <%= link_to t(:started_by, username: topic.user_name? ? topic.user_name.titleize : topic.user.email, default: "Started by #{topic.user_name? ? topic.user_name.titleize : topic.user.email}"), admin_user_path(topic.user.id), remote: true %>
      <%= user_priority(topic.user) %>
      - <%= assigned_to(topic) %>
    </span>
  </td>

  <td class="last-active less-important text-right hidden-xs">
    <span class="label label-count hidden-xs pull-left"><%= topic.posts_count %></span>
    <%= last_active_time(topic.updated_at) %>
  </td>
</tr>

app/views/admin/topics/_topic_options.html.erb
<script>
  Helpy.topicID = <%= @topic.id %>;
</script>
<span class="btn-group left-col-dropdown">
  <button class="status dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
    <%= control_for_status(@topic.current_status) %>
  </button>
  <ul class="dropdown-menu ticket-controls" role="menu">
    <li><%= link_to t(:mark_closed, default: 'Mark Closed'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'closed'), :remote => true, class: 'key-sr' unless @topic.current_status == "closed" %></li>
    <li><%= link_to t(:reopen, default: 'Reopen'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'reopen'), :remote => true, class: 'key-so' unless @topic.current_status == "open" %></li>
    <li><%= link_to t(:mark_new, default: 'Mark New'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'new'), :remote => true, class: 'key-sn' unless @topic.current_status == "new" %></li>
    <li><%= link_to t(:mark_spam, default: 'Mark Spam'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'spam'), :remote => true, class: 'key-ss' unless @topic.current_status == "spam" %></li>
    <li><%= link_to t(:trash, default: 'Trash'), admin_update_topic_path(topic_ids: { "":@topic.id }, change_status: 'trash'), :remote => true, class: 'key-st' unless @topic.current_status == "trash" %></li>
  </ul>
</span>

<% if forums? %>
  <span class="status privacy btn-group left-col-dropdown">
    <button class="privacy-toggle dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
      <%= control_for_privacy(@topic.private?) %>
    </button>
    <ul class="dropdown-menu ticket-controls" role="menu">
      <% Forum.where(private: false).alpha.each do |forum| %>
      <li><%= link_to "#{t(:move_to, default: "Move")}: #{forum.name}", admin_toggle_privacy_path(topic_ids: { "":@topic.id }, private: 'false', forum_id: forum.id), :remote => true %></li>
      <% end %>
      <li><%= link_to "#{t(:mark_as, default: "Mark")}: Private", admin_toggle_privacy_path(topic_ids: { "":@topic.id }, private: 'true', forum_id: 1), :remote => true %></li>
    </ul>
  </span>
<% end %>

<% unless @topic.current_status == "closed" %>
  <span class="status btn-group left-col-dropdown">
    <button class="dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
      <%= content_tag :span, class: 'btn status-label-button label label-warning assign-to' do %>
        <%= @topic.assigned_user.try(:name).try(:upcase) || t(:unassigned, default: 'UNASSIGNED') %>
        <%= icon('caret-down') + ' ' %>
      <% end %>
    </button>
    <ul class="dropdown-menu ticket-controls" role="menu">
      <li><%= link_to "#{current_user.name.titleize}", admin_assign_agent_path(topic_ids: { "":@topic.id }, assigned_user_id: current_user.id), :remote => true unless @topic.current_status == "closed" %></li>
      <li role="separator" class="divider"></li>
      <% (@admins-[current_user]).each do |admin| %>
      <li><%= link_to "#{admin.name.titleize} (#{admin.active_assigned_count})", admin_assign_agent_path(topic_ids: { "":@topic.id }, assigned_user_id: admin.id), :remote => true unless @topic.current_status == "closed" %></li>
      <% end %>
    </ul>
  </span>

  <% if teams? %>
    <span class="status btn-group left-col-dropdown">
      <button class="dropdown-toggle ticket-control" data-toggle="dropdown" aria-expanded="false">
        <%= content_tag(:span, style: badge_color_from_topic(@topic), class: "btn status-label-button group-to label label-#{@topic.team_list.present? ? @topic.team_list.first.first.downcase : 'default'}") do %>
          <%= @topic.team_list.first.try(:upcase) || t(:no_team_assigned, default: 'Assign to group') %>
          <%= icon('caret-down') + ' ' %>
        <% end %>
      </button>
      <ul class="dropdown-menu ticket-controls team-list" role="menu">
        <% @all_teams.to_a.each do |team| %>
          <li class='team-item'>
            <% unless @topic.current_status == "closed" %>
              <%= link_to(color_sample(team), admin_assign_team_path(topic_ids: { "":@topic.id }, team: team), :remote => true) %>
            <% end %>
          </li>
        <% end %>
        <li class="new-tag">
          <%= form_tag '#', class: 'new-group-form' do %>
          <%= text_field_tag "new_group", '', placeholder: "Add a new group", class: 'form-control' %><%#= link_to "Add", '#', class: 'btn btn-default pull-right add-new-group' %>
          <% end %>
        </li>
        <li><%= link_to "Unassign from group", admin_unassign_team_path(topic_ids: { "":@topic.id }, team: ''), :remote => true unless @topic.current_status == "closed" %></li>

      </ul>
    </span>
  <% end %>
<% end %>

app/views/admin/topics/show.html.erb
<% title "#{admin_title} #{t(:discussions, default: 'Discussions')}: #{@topic.id} #{@topic.name.titleize}" %>

<% content_for :pipeline do %>
<%= render partial: 'admin/shared/pipeline' %>
<% end %>

<h2 id="ticket-page-title">
</h2>

<div class="row">
  <div id="tickets" class="col-md-12">
    <%= render 'ticket' %>
  </div>
</div>

app/views/admin/topics/update_ticket.js.erb
$('#tickets').html("<%= escape_javascript(render 'admin/topics/ticket') %>");
$('.ticket-stats').html("<%= j render 'admin/topics/ticket_stats' %>");
history.pushState(null, null, '<%= admin_topic_path @topic %>');

// Update timestamps
$('.last-active time[data-time-ago]').timeago();

// jQuery hook
Helpy.ready();
Helpy.track();

// RTL changes?
<%= "Helpy.rtl();" if rtl? %>